site:
  tab: mujiyu
  title: mujiyu
  description: ğŸŒ¸ è½»ç›ˆã€ä¼˜é›…ã€çº¯å‡€ â€”â€” ç”¨æ–‡å­—ä¸å›¾ç‰‡è®°å½•ç”Ÿæ´»ä¸åˆ›æ„
  language: zh
  favicon: /favicon.ico
  theme:
    light: garden
    dark: dracula
    code: github-dark
  date_format: ddd MMM DD YYYY
  blog:
    pageSize: 8
  banner:
    enableRandom: true
    randomUrl: https://t.alcy.cc/ycy
    randomCount: 5
    height: 60vh
    images:
      - https://tc.alcy.cc/q/20250908/b2d656670551cb9ea6eda7b46b6c8ec0.webp
  icp: ''
  icp_link: ''
  pages:
    home:
      title: RyuChan's Blog
      subtitle: æ¬²ä¹°æ¡‚èŠ±åŒè½½é…’ï¼Œç»ˆä¸ä¼¼ï¼Œå°‘å¹´æ¸¸ï¼
      typewriterTexts:
        - ğŸŒ¸ æ¬²ä¹°æ¡‚èŠ±åŒè½½é…’ï¼Œç»ˆä¸ä¼¼ï¼Œå°‘å¹´æ¸¸ï¼
        - ğŸŒ¸ èŠ±æœ‰é‡å¼€æ—¥ï¼Œäººæ— å†å°‘å¹´ï¼
        - ğŸŒ¿ è®°å½•ç”Ÿæ´»çš„ç‚¹æ»´ï¼Œåˆ†äº«ç¾å¥½çš„ç¬é—´ï¼
        - ğŸ“š çº¸ä¸Šå¾—æ¥ç»ˆè§‰æµ…ï¼Œç»çŸ¥æ­¤äº‹è¦èº¬è¡Œï¼
    friend:
      title: å‹äººå¸
      subtitle: è®°å½•é‚£äº›çè´µçš„å‹è°Šï¼Œåˆ†äº«å½¼æ­¤çš„æ•…äº‹
    about:
      title: About Me
      subtitle: ä¸€ä¸ªçƒ­çˆ±ç”Ÿæ´»ä¸æŠ€æœ¯çš„æ™®é€šäººï¼
    navigation:
      title: ç½‘ç«™å¯¼èˆª
      subtitle: æ”¶è—çš„å¸¸ç”¨ç½‘ç«™å’Œå·¥å…·é“¾æ¥
    anime:
      title: è¿½ç•ª
      subtitle: è®°å½•å’Œåˆ†äº«æˆ‘å–œæ¬¢çš„åŠ¨æ¼«ä½œå“
    project:
      title: Projects
      subtitle: å±•ç¤ºä¸€äº›ä¸ªäººæ­å»ºçš„é¡¹ç›®ï¼Œæ¬è¿å·¥ï¼
    music:
      title: Cloud Music
      subtitle: æ²‰æµ¸å¼äº«å—éŸ³ä¹æ—¶å…‰
  menu:
    - id: home
      text: é¦–é¡µ
      href: /
      svg: material-symbols:home-outline-rounded
      target: _self
    - id: write
      text: å†™ä½œ
      href: /write
      svg: material-symbols:edit-square-outline-rounded
      target: _self
    - id: navigation
      text: å¯¼èˆª
      href: /navigation
      svg: material-symbols:explore-outline
      target: _self
    - id: entertainment
      text: å¨±ä¹
      href: '#'
      svg: material-symbols:play-circle-outline-rounded
      target: _self
      subItems:
        - id: anime
          text: è¿½ç•ª
          href: /anime
          svg: material-symbols:movie-outline
          target: _self
        - id: music
          text: éŸ³ä¹
          href: /music
          svg: material-symbols:music-note-rounded
          target: _self
    - id: project
      text: é¡¹ç›®
      href: /project
      svg: material-symbols:code-blocks-outline
      target: _self
    - id: friend
      text: å‹äººå¸
      href: /friend
      svg: material-symbols:supervisor-account-outline-rounded
      target: _self
    - id: about
      text: å…³äº
      href: /about
      svg: material-symbols:info-outline-rounded
      target: _self
anime:
  bilibili:
    uid: '1536411565'
  tmdb:
    apiKey: 08a6bef260044f70c150251c79f2e476
    listId: '8556173'
github:
  owner: kobaridev
  repo: RyuChan
  branch: main
  appId: åœ¨éƒ¨ç½²ç«¯é…ç½®ç¯å¢ƒå˜é‡
  encryptKey: wudishiduomejimo
umami:
  enable: true
  baseUrl: www.mzyft.top
  shareId: PItOR8pvbZ06KYc9
  websiteId: d8f2ea63-1e48-43bc-af1d-07b19c069f28
  timezone: Asia/Shanghai
user:
  name: mujiyu
  description: 'è¯·æ°¸è¿œä¸è¦ä¸º2å°æ—¶ä»¥åå’Œ8å…¬é‡Œä¹‹å¤–çš„äº‹æƒ…æ‹…å¿§ã€‚å–œæ¬¢çš„æ˜æ˜Ÿ: @é»„æ™¯ç‘œ @å­™åƒ @ææŸ¯ä»¥Sylph @ç‹åŸ¹å»¶babyğŸ²'
  site: https://hub.xiaozhangya.xin
  avatar: /profile.png
  sidebar:
    social:
      - href: https://qm.qq.com/q/ohrx27Li12
        ariaLabel: QQ
        title: QQ
        svg: ri:qq-line
      - href: 1719395375@qq.com
        ariaLabel: Email
        title: Email
        svg: ri:mail-line
      - href: https://v.douyin.com/2rLUABfbRjU/ 2@1.com
        ariaLabel: Douyin
        title: Douyin
        svg: ri:tiktok-line
      - href: https://weibo.com/u/5908343897
        title: Weibo
        ariaLabel: Weibo
        svg: ri:weibo-fill
      - href: https://space.bilibili.com/3493122409498928?spm_id_from=333.1007.0.0
        title: Bilibili
        ariaLabel: Bilibili
        svg: ri:bilibili-line
  footer:
    social:
      - href: https://github.com/kobaridev
        ariaLabel: Github
        title: Github
        svg: ri:github-line
      - href: https://space.bilibili.com/1536411565
        ariaLabel: BiliBili
        title: BiliBili
        svg: ri:bilibili-line
      - href: https://x.com/xzz_ya
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: ri:twitter-line
      - href: https://t.me/xzz_ya
        ariaLabel: Telegram
        title: Telegram
        svg: ri:telegram-line
comments:
  enable: true
  type: giscus
  giscus:
    repo: kobaridev/gsc
    repoId: R_kgDOPTM-mA
    category: General
    categoryId: DIC_kwDOPTM-mM4CtcFq
    mapping: pathname
    lang: zh-CN
    inputPosition: top
    reactionsEnabled: '1'
    emitMetadata: '0'
    loading: lazy
  waline:
    serverURL: https://your-waline-server
    lang: zh-CN
    emoji:
      - https://unpkg.com/@waline/emojis@1.1.0/weibo
      - https://unpkg.com/@waline/emojis@1.1.0/bilibili
    meta:
      - nick
      - mail
      - link
    requiredMeta: []
    reaction: false
    pageview: false
